# Coursework 2

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [1]:
using JLD2,FileIO

In [2]:
Base.@kwdef mutable struct CourseWork_2
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    
    # 7.1 Estimation Accuracy
    
    Q7_1_data_A::Matrix{Float64}
    
    Q7_1_a_ans_w::Union{Missing,Vector}
    Q7_1_a_ans_err::Union{Missing,Float64}
    Q7_1_b_ans_w::Union{Missing,Vector}
    Q7_1_b_ans_err::Union{Missing,Float64}
    Q7_1_c_ans_err::Union{Missing,Float64}
    
     # 7.2 Greedy Algorithms
    
    Q7_2_1_data_y::Vector
    Q7_2_1_data_A::Matrix
    Q7_2_1_data_S::Int
    
    Q7_2_1_ans_x::Union{Missing,Vector}
    
    Q7_2_2_data_y::Vector
    Q7_2_2_data_A::Matrix
    Q7_2_2_data_S::Int
    
    Q7_2_2_ans_x::Union{Missing,Vector}
    
    Q7_2_3_data_y::Vector
    Q7_2_3_data_A::Matrix
    Q7_2_3_data_S::Int
    
    Q7_2_3_ans_x::Union{Missing,Vector}
    
    # 8.1 The MOD Method
    
    Q8_1_data_Y::Matrix
    Q8_1_data_D0::Matrix
    Q8_1_data_C0::Matrix
    Q8_1_data_s::Int
    
    Q8_1_1_ans_Comp::Union{Missing,Matrix}
    Q8_1_2_ans_Csp::Union{Missing,Matrix}
    Q8_1_3_ans_Dmod::Union{Missing,Matrix}
    Q8_1_4_ans_C50::Union{Missing,Matrix}
    Q8_1_4_ans_D50::Union{Missing,Matrix}
    Q8_1_5_ans_f::Union{Missing,Vector}
    Q8_1_5_ans_gradf::Union{Missing,Vector}
    
    # 8.2 The K-SVD Method
    
    Q8_2_data_Y::Matrix
    Q8_2_data_D0::Matrix
    Q8_2_data_C0::Matrix
    Q8_2_data_s::Int
    
    Q8_2_1_ans_Ckscd::Union{Missing,Matrix}
    Q8_2_1_ans_Dkscd::Union{Missing,Matrix}
    Q8_2_2_ans_C50::Union{Missing,Matrix}
    Q8_2_2_ans_D50::Union{Missing,Matrix}
    Q8_2_3_ans_f::Union{Missing,Vector}
    Q8_2_3_ans_gradf::Union{Missing,Vector}
    
    
end

CourseWork_2

In [3]:



A = JLD2.load("Banthia Dev2016674StudentFile.jld2");

A = A["CourseWork_2"];

A
 

# jldopen("xxx.jld2", "w") do file

#    write(file, "CourseWork_2", A)

# end

CourseWork_2(2016674, missing, [6.241721161255183 4.3833479018275625 … 4.723291032514396 4.914933966242956; 4.3833479018275625 5.3441149344285925 … 4.036482479841339 4.420052371130021; … ; 4.723291032514396 4.036482479841339 … 5.556818064841123 5.449901584843792; 4.914933966242956 4.420052371130021 … 5.449901584843792 6.290400040766449], missing, missing, missing, missing, missing, [-0.3215142162434899, -0.20743986111955076, -0.30010762842848554, -0.1939895552625288, -0.01582866928981454, 0.28938805764103565, -0.28713189963215413, 0.41984134379947163, 0.08984779465282412, 0.14479291759338486  …  0.40827803074088553, -0.18181724355398374, -0.19863724476373407, -0.2992676053064818, 0.787511268319871, -0.07480016676901381, 0.09416225164505233, -0.2368429034702739, 0.23901562132959572, 0.06080053200024716], [0.18395762760195788 0.02944481109789814 … 0.2989090159651482 -0.08513575777754952; 0.0015069902494225485 0.15299668583435583 … 0.22196583253548793 0.21083156219927665; … ; 0.2260985225

## 7.1. Estimation Accuracy


### 1. (a)

In [64]:
# save your answers in Q7_1_a_ans_w and Q7_1_a_ans_err
A_matrix = A.Q7_1_data_A
    
println(size(A_matrix))
    

(16, 16)


### 1. (b)

In [ ]:
# save your answers in Q7_1_b_ans_w and Q7_1_b_ans_err


### 1. (c)

## 7.2. Greedy Algorithms

### 1

In [4]:
using LinearAlgebra


y = A.Q7_2_1_data_y
A_matrix = A.Q7_2_1_data_A
S = A.Q7_2_1_data_S


function compute_best_fit_solution(X, y)
    return X \ y  
end

function expand_support(A, y, k, sparse_set)
    correlation = A' * y
    top_k = partialsortperm(abs.(correlation), length(correlation) - k + 1:length(correlation))
    sparse_set = union(sparse_set, Set(top_k))

    return sparse_set
end

function OMP(A, y, S)
    sparse_set = Set{Int}()
    residual = y
    sparse_solution = zeros(size(A, 2))
    x_hat = zeros(length(S))
    
    for i in 1:S
        correlation = A' * residual
        S_max = sortperm(abs.(correlation), rev=true)[i]
        push!(sparse_set, S_max)

        col_indices = collect(sparse_set)
        A_subset = A[:, col_indices]

        x_hat = compute_best_fit_solution(A_subset, y)

    end

    for (i, j) in zip(sparse_set, x_hat)
        sparse_solution[i] = j
    end

    return sparse_solution
end

sparse_solution = OMP(A_matrix, y , S)
residual = y - A_matrix * sparse_solution
println(sum(abs.(residual)))

7.3240900597645755


### 2

In [22]:
function SMP(A, y, k, C = nothing)

    sparse_set = Set()
    sparse_solution = zeros(size(A, 2))

    if C == nothing 
        sparse_set = expand_support(A, y, k, sparse_set)
  

    else
        residual = y - A*C
        sparse_set = expand_support(A, residual, k, sparse_set)
    end

    A_subset = A[:, collect(sparse_set)]
    x_hat = compute_best_fit_solution(A_subset, y)
    residual = y - A_subset * x_hat


    n = 10
    for i in 1:n 
        sparse_set = expand_support(A, residual, k, sparse_set)
        A_subset = A[:, collect(sparse_set)]
        x_hat = compute_best_fit_solution(A_subset, y)
        
        # Get k most significant indices
        k_most_significant_x = partialsortperm(abs.(x_hat), 1:k, rev=true)
        sparse_set = Set(collect(sparse_set)[k_most_significant_x])
        
        A_subset = A[:, collect(sparse_set)]
        x_hat = compute_best_fit_solution(A_subset, y)
        residual = y - A_subset * x_hat
    end

    for (i, j) in zip(sparse_set, x_hat)
        sparse_solution[i] = j
    end

    return sparse_solution

end

SMP(A_matrix, y, 5)



74-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 1.0651807642497881
 0.0
 0.0
 0.0
 0.0
 0.0

### 3

In [17]:
using LinearAlgebra

function HIT(A, y, k)
    x = zeros(size(A, 2)) 

    for i in 1:10000

        x -= 0.01 * (A' * (A * x - y))

        top_k_indices = partialsortperm(abs.(x), length(x) - k + 1:length(x))
        x[setdiff(1:end, top_k_indices)] .= 0
    end

    return x
end


x = HIT(A_matrix, y, S)


13.006710713649106
12.843499078766252
12.682784551161301
12.524526669756515
12.368685643382026
12.215222339583647
12.064098273618468
11.915275597635135
11.76871709003568
11.624386145015853
11.48224676228095
11.342263536934206
11.204401649534818
11.068626856322776
10.934905479607638
10.803204398318595
10.673491038713006
10.548765751061557
10.42868766411305
10.310393212753889
10.193853768579215
10.079051518162654
9.972385205963901
9.867260856413779
9.763653898024907
9.66154016434901
9.560895887217882
9.46169769009777
9.363922581555222
9.274165981353104
9.193754358041053
9.11443671539754
9.036196040208132
8.959015597007555
8.882878923465208
8.807769825847837
8.733672374558171
8.66057089974822
8.588449987005928
8.517294473114037
8.447089441879873
8.377820220034902
8.309472373202892
8.242031701935476
8.175484237814066
8.10981623961692
8.045014189550336
7.981064789542851
7.917954957601402
7.855671824228439
7.794202728898894
7.733535216596077
7.673657034405475
7.614556128165479
7.556220639174

74-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 1.0963889168969245
 0.0
 0.0
 0.0
 0.0
 0.0

## 8.1. The MOD Method

### 1

In [9]:
Y = A.Q8_1_data_Y
D0 = A.Q8_1_data_D0
C0 = A.Q8_1_data_C0
s = A.Q8_1_data_s

function construct_C_omp(D0, Y, s)

    num_rows = size(D0, 2)
    num_cols = size(Y, 2)
    C_omp = zeros(num_rows, num_cols)

    for i in 1:num_cols
        sparse_col = OMP(D0, Y[:,i], s)
        C_omp[:, i] = sparse_col
    
    end

    return C_omp

end
    

# C_omp = construct_C_omp(D0, Y, s)
# residual = abs.(Y - D0*C_omp)



[0.0, 0.0, 2.026542257906963, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.7404803582137154, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.2341465769704425, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.4842604166759696, 1.6655611299924797, 0.0]

### 2

In [30]:
function construct_C_smp(D0, Y, s, C0 = nothing)

    num_rows = size(D0, 2)
    num_cols = size(Y, 2)
    C_smp = zeros(num_rows, num_cols)

    for i in 1:num_cols

        if C0 != nothing
            sparse_col = SMP(D0, Y[:,i], s, C0[:, i])
        else
            sparse_col = SMP(D0, Y[:,i], s)
        
        end

        C_smp[:, i] = sparse_col
    
    end

    return C_smp

end

residual = abs.(Y - D0*C0)
println(sum(residual))

C_smp = construct_C_smp(D0, Y, s, C0)
residual = abs.(Y - D0*C_smp)
println(sum(residual))

18376.236105330903
2094.2245309606624


### 3

In [33]:
function DU_mod(Y, C)

    return Y * C' * inv(C * C')
end

D1 = DU_mod(Y, C0)

32×64 Matrix{Float64}:
  0.0640119   0.03824     0.0815572  -0.151439   …   0.121214   -0.440008
  0.138344    0.0296396  -0.14766    -0.158758       0.0819415  -0.45457
  0.138205    0.111268   -0.399663   -0.202758       0.015491   -0.331456
 -0.169242   -0.050029   -0.167438    0.434493      -0.421986   -0.369665
 -0.0582565   0.131329   -0.341002    0.095262      -0.0952771   0.200773
  0.0131542   0.0280688  -0.210033    0.339975   …   0.380503   -0.126959
  0.0676639  -0.240581    0.214364    0.263229       0.252141    0.313172
 -0.426405   -0.0770443  -0.361647   -0.199696      -0.160853    0.160509
  0.193734   -0.0773045   0.126287    0.228234      -0.16662     0.112615
 -0.104221   -0.0588115   0.0055561   0.082641      -0.542094   -0.124269
  ⋮                                              ⋱              
 -0.120532    0.260977   -0.154781   -0.037346      -0.236694    0.190147
 -0.427421   -0.0995458  -0.124972   -0.0413386     -0.135161   -0.0987127
 -0.362939    0.0326951 

### 4

In [39]:
function MOD(Y, D0, C0)

    D = D0
    C_smp = C0
    for i in 1:50

        residual = abs.(Y - D*C_smp)
        println(sum(residual))
        C_smp = construct_C_smp(D, Y, s, C_smp)
        D = DU_mod(Y, C_smp) 

    end

    return C_smp, D
end

MOD(Y, D0, C0)

18376.236105330903
1467.5459803748379
1190.2089857007777
1067.2979782893726
1029.5094842944281
1006.550177904018
973.1644014769306
923.8759537231479
938.865349732386
920.0495472826033
910.1598519880974
888.2182207826916
866.7113857069965
871.3682176848885
864.3079671988335
849.3851682086963
845.3282524150966
860.6083038590398
846.766854143348
845.1219737774941
825.6932330632293
813.5314882696782
806.8922454480356
798.4434217192298
811.8557250257412
805.767464495585
792.7872410588319
788.104850289228
802.701934688966
799.8248913708318
800.9615568441945
816.9853328363808
805.7122982421223
783.9971563678441
799.644435691518
812.0370066508551
801.4476318667632
781.9722568670828
790.9708025982375
776.496785870303
774.2494512047491
766.6379025368294
770.9104211448378
769.1543129852256
805.2783096898527
794.5820573909847
803.089329159379
807.5530473861331
829.2272436082851
796.6736181399017


([0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [-4.421185806378285 -1.7086233330544016 … 4.415717672262828 -0.2495166562968832; -5.536335807824002 -3.8891254900399383 … -5.70087409487256 6.140680440851347; … ; -3.3026330755657534 3.2256987653131426 … -3.2165905610164542 1.4418233965211045; 6.279352477161184 -3.02316904917303 … 0.014777468619201335 -3.0283263830927005])

### 5

## 8.1. The K-SVD Method

### 1

### 2

### 3