# Coursework 2

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [1]:
using JLD2,FileIO

In [2]:
Base.@kwdef mutable struct CourseWork_2
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    
    # 7.1 Estimation Accuracy
    
    Q7_1_data_A::Matrix{Float64}
    
    Q7_1_a_ans_w::Union{Missing,Vector}
    Q7_1_a_ans_err::Union{Missing,Float64}
    Q7_1_b_ans_w::Union{Missing,Vector}
    Q7_1_b_ans_err::Union{Missing,Float64}
    Q7_1_c_ans_err::Union{Missing,Float64}
    
     # 7.2 Greedy Algorithms
    
    Q7_2_1_data_y::Vector
    Q7_2_1_data_A::Matrix
    Q7_2_1_data_S::Int
    
    Q7_2_1_ans_x::Union{Missing,Vector}
    
    Q7_2_2_data_y::Vector
    Q7_2_2_data_A::Matrix
    Q7_2_2_data_S::Int
    
    Q7_2_2_ans_x::Union{Missing,Vector}
    
    Q7_2_3_data_y::Vector
    Q7_2_3_data_A::Matrix
    Q7_2_3_data_S::Int
    
    Q7_2_3_ans_x::Union{Missing,Vector}
    
    # 8.1 The MOD Method
    
    Q8_1_data_Y::Matrix
    Q8_1_data_D0::Matrix
    Q8_1_data_C0::Matrix
    Q8_1_data_s::Int
    
    Q8_1_1_ans_Comp::Union{Missing,Matrix}
    Q8_1_2_ans_Csp::Union{Missing,Matrix}
    Q8_1_3_ans_Dmod::Union{Missing,Matrix}
    Q8_1_4_ans_C50::Union{Missing,Matrix}
    Q8_1_4_ans_D50::Union{Missing,Matrix}
    Q8_1_5_ans_f::Union{Missing,Vector}
    Q8_1_5_ans_gradf::Union{Missing,Vector}
    
    # 8.2 The K-SVD Method
    
    Q8_2_data_Y::Matrix
    Q8_2_data_D0::Matrix
    Q8_2_data_C0::Matrix
    Q8_2_data_s::Int
    
    Q8_2_1_ans_Ckscd::Union{Missing,Matrix}
    Q8_2_1_ans_Dkscd::Union{Missing,Matrix}
    Q8_2_2_ans_C50::Union{Missing,Matrix}
    Q8_2_2_ans_D50::Union{Missing,Matrix}
    Q8_2_3_ans_f::Union{Missing,Vector}
    Q8_2_3_ans_gradf::Union{Missing,Vector}
    
    
end

CourseWork_2

In [3]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/

 

# Example

data = JLD2.load("Browne Liam1943834StudentFile.jld2");

data = data[ "CourseWork_2" ];


 

# jldopen("xxx.jld2", "w") do file

#    write(file, "CourseWork_2", A)

# end

CourseWork_2(1943834, missing, [4.2139137101022985 3.587852118477784 … 3.144509047464645 3.784994172304772; 3.587852118477784 7.163636332100328 … 5.113022329729536 6.344465937225596; … ; 3.144509047464645 5.113022329729536 … 5.683010637763987 5.222604582405985; 3.784994172304772 6.344465937225596 … 5.222604582405985 6.756776585140605], missing, missing, missing, missing, missing, [0.2832818459371857, 0.14252805069498312, -0.5078137248277569, -0.04309048824627739, -0.8470982690553306, -0.1197558443049093, -0.0111059514717404, 0.6522917421360365, 0.3879652120489858, 0.21397925379596952  …  -0.36363029668323554, -0.9304188076436458, -0.03767912300966174, -0.014742857359932679, -0.12280842325563851, -0.6146126458066495, -0.3205057664892471, -0.5434728332603277, -0.03161896114753292, 0.5748632405988965], [0.030008364877164385 -0.3102381714775882 … 0.2801497617094742 -0.014371445785814953; 0.10715370373678043 -0.16758692836078676 … -0.13205740184011666 0.001319465404622215; … ; -0.0519757132

## 7.1. Estimation Accuracy


### 1. (a)

In [4]:
# save your answers in Q7_1_a_ans_w and Q7_1_a_ans_err
using LinearAlgebra

A = data.Q7_1_data_A
A_hat = inv(adjoint(A) * A) * adjoint(A)
A_hat_SVD = svd(A_hat)

S = A_hat_SVD.S
V = A_hat_SVD.V

w_min = V[:, end]
println(norm(w_min))
println(w_min)

sol = adjoint(A_hat * w_min) * (A_hat * w_min)
# Test solution
# println(sol)
# println(S[end]*S[end])


1.0
[-0.22358732935485137, -0.34758370129967936, -0.30117137298843794, -0.24928900741392682, -0.22451467440516168, -0.25234222520905747, -0.2628887107176502, -0.27050935138069576, -0.23075989861576957, -0.2810051684020147, -0.2109952531370861, -0.2335664558916708, -0.2795307902445785, -0.33249370855246135]
0.0003564207643761831
0.0003564207643760726


### 1. (b)

In [31]:
# save your answers in Q7_1_b_ans_w and Q7_1_b_ans_err
A = data.Q7_1_data_A
A_hat = inv(adjoint(A) * A) * adjoint(A)
A_hat_SVD = svd(A_hat)

S = A_hat_SVD.S
V = A_hat_SVD.V

w_max = V[:, 1]
println(norm(w_max))
println(w_max)

sol = adjoint(A_hat * w_max) * (A_hat * w_max)

# Test solution
# println(sol)
# println(S[1]*S[1])

0.9999999999999998
[-0.0320466983291685, 0.037842986098476895, 0.02970274462016937, -0.2604433836321299, 0.45951640780659525, 0.10494135589302148, -0.2209146167363501, -0.12819899890848124, 0.07916874300703276, 0.5627950731056846, -0.04214372955892949, -0.44154235329594393, -0.32723291168213886, 0.1208243916599795]
79157.61419919424
79157.61419919421


### 1. (c)

In [33]:
A_hat = inv(adjoint(A) * A) * adjoint(A)
# Using expectation of quadratic form
Exp = tr(adjoint(A_hat) * A_hat) / size(A_hat, 1)

5788.248295044012

## 7.2. Greedy Algorithms

### 1

In [7]:
y = data.Q7_2_1_data_y
A = data.Q7_2_1_data_A
S = data.Q7_2_1_data_S

# println(size(y))
# println(size(A))
# println(S)

function greedy_OMP(y, A, S)
    l = 1
    x_hat = zeros(size(A)[2])
    
    y_r = y
    T_l = []

    while(l <= S)
        i_l = argmax(abs.(adjoint(A) * y_r))
        push!(T_l, i_l)
        
        A_l = zeros(size(A)[1], length(T_l))
        

        for i in 1:length(T_l)
            A_l[:, i] = A[:, T_l[i]]
        end
       
        x_hat_T_l = pinv(A_l) * y

        for i in 1:length(T_l)
            x_hat[T_l[i]] = x_hat_T_l[i]
        end

        y_r = y - (A * x_hat)

        # mse = norm(y_r)^2 / length(y)

        # println("MSE $l: $mse ")

        l = l + 1
    end
    
    return x_hat
end

greedy_OMP(y, A, S)


100-element Vector{Float64}:
 1.9121021675178456
 0.0
 0.0
 0.0
 0.0
 1.5702793501276053
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

### 2

In [8]:
y = data.Q7_2_2_data_y
A = data.Q7_2_2_data_A
S = data.Q7_2_2_data_S

# println(size(y))
# println(size(A))
# println(S)

function greedy_SP(y, A, S, c0=nothing)
    # Initialisation:
    if (c0 === nothing)
        T0 = sortperm(abs.(adjoint(A) * y), rev=true)[1:S]
    else
        T0 = sortperm(abs.(c0), rev=true)[1:S]
    end
    filter!(p -> p != 0, T0)
    A_T0 = zeros(size(A)[1], length(T0))
    for i in 1:length(T0)
        A_T0[:, i] = A[:, T0[i]]
    end

    x_hat_T0 = pinv(A_T0) * y

    y_r = y - (A_T0 * x_hat_T0)
    Tl = T0
    xl = zeros(size(A)[2])
    
    # Iterate until convergence
    for l in 1:4
        # mse = norm(y_r)^2 / length(y)
        # println("MSE $l: $mse ")

        # Step 3
        # Union of T_l-1 and highest-correlated columns of A with (y) residue
        Ttildal = append!(Tl, sortperm(abs.(adjoint(A) * y_r), rev=true)[1:S])
        filter!(p -> p != 0, T0)
        # Step 4
        # Constructing b
        A_Ttildal = zeros(size(A)[1], length(Ttildal))

        for i in 1:length(Ttildal)
            A_Ttildal[:, i] = A[:, Ttildal[i]]
        end

        b_Ttildal = pinv(A_Ttildal) * y

        b = zeros(size(A)[2])

        for i in 1:length(Ttildal)
            b[Ttildal[i]] = b_Ttildal[i]
        end

        # Step 5
        # Update Tl
        Tl = sortperm(abs.(b), rev=true)[1:S]
        filter!(p -> p != 0, Tl)
        # Step 6
        # Update xl
        A_Tl = zeros(size(A)[1], length(Tl))
        for i in 1:length(Tl)
            A_Tl[:, i] = A[:, Tl[i]]
        end

        xl_Tl = pinv(A_Tl) * y

        xl = zeros(size(A)[2])

        for i in 1:length(Tl)
            xl[Tl[i]] = xl_Tl[i]
        end

        y_r = y - (A * xl)
    end

 
    return xl

end

greedy_SP(y, A, S)


98-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.723647645324772
 1.165916081091429
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.6024695392678504
 0.0
 0.0
 0.0
 0.0

### 3

In [22]:
y = data.Q7_2_3_data_y
A = data.Q7_2_3_data_A
S = data.Q7_2_3_data_S

function greedy_HIT(y, A, S)

    # Initialisation
    x0 = zeros(size(A)[2])
    xl = x0

    mse = norm(y - (A * xl))^2 / length(y)
    println("MSE 0: $mse ")
    # For Loop
    for l in 1:1
        xl = (xl + (adjoint(A) * (y - (A * xl))))
        x_ind = sortperm(abs.(xl), rev=true)[1:S]

        xl_sp = zeros(length(xl))
        for i in 1:length(x_ind)
            xl_sp[x_ind[i]] = xl[x_ind[i]]
        end

        xl = xl_sp

        mse = norm(y - (A * xl))^2 / length(y)
        println("MSE $l: $mse ")
    end

    return xl
end

greedy_HIT(y, A, S)

MSE 0: 0.20284477913101934 
MSE 1: 0.1043997898997661 


72-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

## 8.1. The MOD Method

### 1

In [10]:
Y = data.Q8_1_data_Y
D0 = data.Q8_1_data_D0
C0 = data.Q8_1_data_C0
s = data.Q8_1_data_s

# println(size(Y))
# println(size(D0))
# println(size(C0))
# println(s)

# println(C0)




function SC_OMP(Y, D0, s)
    Comp = zeros(size(D0)[2], size(Y)[2])
    
    for i in 1:size(Comp)[2]
        y = Y[:, i]
        Cn = greedy_OMP(y, D0, s)
        Comp[:, i] = Cn
    end

    return Comp
end

SC_OMP(Y, D0, s)

64×128 Matrix{Float64}:
 0.0       0.0   0.0      0.0       …   0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0       -0.259481
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 0.0       0.0   0.0      0.196751      0.0        0.0        0.274295
 0.0       0.0   0.0      0.0       …   0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 ⋮                                  ⋱   ⋮                    
 0.0       0.0   0.0      0.0       …   0.0        0.0        0.0
 0.0       0.0   0.0      0.0           0.0        0.0        0.0
 0.0       0.0   0.0     -0.267059      0.0       -0.344977   0.0
 0.0       0.0   0.0      0.0          -0.2804

### 2

In [11]:
function SC_SP(Y, D0, C0, s)
    Csp = zeros(size(D0)[2], size(Y)[2])
    
    for i in 1:size(Csp)[2]
        y = Y[:, i]
        c0 = C0[:, i]
        Cn = greedy_SP(y, D0, s, c0)
        Csp[:, i] = Cn
    end

    return Csp
end

SC_SP(Y, D0, C0, s)

64×128 Matrix{Float64}:
 0.0       0.0  0.832398   0.0       …   0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0       -0.283698
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.28643
 0.0       0.0  0.0        0.272794  …   0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 ⋮                                   ⋱   ⋮                   
 0.0       0.0  0.0        0.0       …   0.0       0.0        0.0
 0.0       0.0  0.0        0.0           0.0       0.0        0.0
 0.262642  0.0  0.0       -0.246193     -0.283137  0.0        0.0
 0.0       0.0  0.0        0.0          -0.3849

### 3

In [12]:
function DU_MOD(Y, Dcurr, Ccurr, s)
    Cnext = SC_SP(Y, Dcurr, Ccurr, s)

    # Solving least squares
    Dmod = Y * adjoint(Cnext) * inv((Cnext * adjoint(Cnext)))

    # Normalise D
    for i in 1:size(Dmod)[2]
        Dmod[:, i] /= norm(Dmod[:, i], 2)
    end

    return Dmod
end

DU_MOD(Y, D0, C0, s)

32×64 Matrix{Float64}:
  0.0361446  -0.0273042   -0.153877   …  -0.30371      0.041344
 -0.0867692   0.143373     0.046204      -0.132403    -0.0826498
 -0.0431085  -0.334189    -0.0819584      0.0546316   -0.193791
  0.0173427   0.12157     -0.112688      -0.257564    -0.000453293
 -0.178962   -0.00713662  -0.0107781      0.107444    -0.0546023
 -0.0892475  -0.228888    -0.0715238  …  -0.020939    -0.233215
  0.168909    0.342775     0.194087      -0.178278     0.0398617
  0.347153   -0.120417    -0.175526      -0.139337    -0.078367
 -0.0751593  -0.038332    -0.0965354      0.349831     0.140895
 -0.153309    0.113698     0.0437212      0.203842     0.00769751
  ⋮                                   ⋱               
 -0.205823    0.012513     0.0530759      0.214387     0.0797941
 -0.0156221   0.146611    -0.379342      -0.124546     0.264049
  0.501375    0.00754822   0.233174   …  -0.0827245    0.00109206
  0.0816713  -0.238426     0.0773764      0.014662     0.198374
  0.0851532  -0

### 4

In [13]:
using LinearAlgebra

Y = data.Q8_1_data_Y
D0 = data.Q8_1_data_D0
C0 = data.Q8_1_data_C0
s = data.Q8_1_data_s

# Number of iterations
iter = 50

# Initialisation
Ccur = C0
Dcur = D0

for i in 1:iter
    Cnext = SC_SP(Y, Dcur, Ccur, s)
    Dcur = DU_MOD(Y, Dcur, Ccur, s)
    Ccur = Cnext

    # Uncomment to print error
    err = norm(Y - (Dcur * Ccur))^2 / length(Y)
    println("Error $i: $err")
end



Error 1: 0.7758770384615739
Error 2: 0.15223580896394698
Error 3: 0.13527370490566218
Error 4: 0.1255356960505468
Error 5: 0.11969352095912181
Error 6: 0.11385004734618501
Error 7: 0.10918205219905618
Error 8: 0.10612933675727754
Error 9: 0.10368415176718877
Error 10: 0.10116035952518451
Error 11: 0.09928599935718219
Error 12: 0.09805034087725914
Error 13: 0.09721526870391552
Error 14: 0.09659612420821233
Error 15: 0.09611329393477448
Error 16: 0.09557402641186784
Error 17: 0.09507110119810867
Error 18: 0.0947056189085764
Error 19: 0.09402189015781363
Error 20: 0.09362192898504536
Error 21: 0.09334726333758002
Error 22: 0.09313385910950685
Error 23: 0.092855941571146
Error 24: 0.09263526308924064
Error 25: 0.09176529346806948
Error 26: 0.09116044568429829
Error 27: 0.09059570094458058
Error 28: 0.09001814047626679
Error 29: 0.08940309963683085
Error 30: 0.08899371817582978
Error 31: 0.08858652291891078
Error 32: 0.08814352391864005
Error 33: 0.08768273046826043
Error 34: 0.086810898556

### 5

In [14]:
using LinearAlgebra

Y = data.Q8_1_data_Y
D0 = data.Q8_1_data_D0
C0 = data.Q8_1_data_C0
s = data.Q8_1_data_s


function f_and_gradf(Y, D, C)
    f = (norm(Y - (D * C)))^2
    grad = 2 * adjoint(D) * (Y - (D*C))
    norm_grad = norm(grad)

    # println("f: $f, normgrad: $norm_grad")

    return f, norm_grad
end

# Number of iterations
iter = 50

# Initialisation
Ccur = C0
Dcur = D0

for i in 1:iter
    f_and_gradf(Y, Dcur, Ccur)
    Cnext = SC_SP(Y, Dcur, Ccur, s)
    Dcur = DU_MOD(Y, Dcur, Ccur, s)
    Ccur = Cnext

    # Uncomment to print error
    # err = norm(Y - (Dcur * Ccur))^2 / length(Y)
    # println("Error $i: $err")
end

## 8.1. The K-SVD Method

### 1

In [20]:
using LinearAlgebra

Y = data.Q8_2_data_Y
D0 = data.Q8_2_data_D0
C0 = data.Q8_2_data_C0
s = data.Q8_2_data_s

println(size(Y))
println(size(D0))
println(size(C0))
println(s)

function old(Y, D0, Csp)

    # Step a) Find W, each row is the number of non-zero elements in kth row of Csp
    W = []
    for k in 1:size(Csp)[1]
        w_k = []
        for n in 1:size(Csp)[2]
            if (Csp[k, n] != 0)
                push!(w_k, n)
            end
        end
        
        push!(W, w_k)
    end
    
    # Step b) Compute representation error matrices
    E_tensor = []
    
    for k in 1:size(Csp)[1]
        Ek = zeros(size(Y))
        # if(W[k][1] != size(Csp)[2]+1)
        if(!isempty(W[k]))
            for p in 1:size(Csp)[1]
                if (p != k)
                    Ek = Ek + D0[:, p] * Csp[p, :]'
                end
            end
        end
        push!(E_tensor, Ek)
    end

    # Step c) Restrict columns of error matrices
    Ekw_tensor = []
    for k in 1:length(E_tensor)
        Ekw = zeros(size(Y)[1], length(W[k]))
        # if(W[k][1] != size(Csp)[2]+1)
        if(!isempty(W[k]))
            for j in 1:length(W[k])
                Ekw[:, j] = E_tensor[k][:, W[k][j]]
            end
        end
        push!(Ekw_tensor, Ekw)
    end
    
    # Step d) SVD and updating
    Dksvd = zeros(size(D0))
    Cksvd = zeros(size(Csp))
    # Cksvd = Csp
    
    for k in 1:size(D0)[2]
        # if(W[k][1] != size(Csp)[2]+1)
        if(!isempty(W[k]))
            decomp = svd(Ekw_tensor[k])

            Dksvd[:, k] = decomp.U[:, 1]
            for j in 1:length(W[k])
                Cksvd[k, W[k][j]] = decomp.S[1] * decomp.V[j, 1]
            end
        end
    end

    return Dksvd, Cksvd

end

function DU_KSVD(Y, D0, Csp)
    K = size(D0, 2)
    N = size(Csp, 2)
    
    D_ksvd = zeros(size(D0))
    C_ksvd = zeros(size(Csp))

    for k in 1:K
        Csp_k = Csp[k, :]
        w_k = [n for n in 1:N if Csp_k[n] != 0]
        
        subset = [p for p in 1:K if p != k]
        Dsub = D0[:, subset]
        Csub = Csp[subset, :]

        E_k = Y - Dsub * Csub
        E_kw = E_k[:, w_k]

        U, s, V = svd(E_kw)

        d_svd = U[:, 1]
        c_svd = s[1] * V[:, 1]

        D_ksvd[:, k] = d_svd
        C_ksvd[k, w_k] = c_svd
    end

    return D_ksvd, C_ksvd

end

DU_KSVD(Y, D0, C0)

(32, 128)
(32, 64)
(64, 128)
5


([-0.07143289475618317 0.048731106970497706 … -0.038861705695025756 -0.044155623760027574; 0.0011368173476388804 0.0868035641387671 … -0.0857518119824881 -0.09704802369889996; … ; -0.2431390072415944 0.3457128241158718 … -0.34156286845230316 -0.35026208778449347; -0.11623930793650553 -0.04402204295610815 … 0.04472051579547413 0.04731977626605716], [-6.663504160826699 6.310261049783611 … -2.4881039324820646 -2.6545135900648917; 1.6015689996219324 -0.12092004503969438 … 3.480508876218752 1.6881859535838712; … ; -1.7023419172866512 -0.20564604034361708 … -3.4036217159939857 -1.4642116183152714; -1.5690091987132608 0.041355819280295435 … -3.4345635301130395 -1.859468703551903])

### 2

In [21]:

# Initialisation
iter = 50
Dksvd = D0
Cksvd = C0

for i in 1:iter
    # Uncomment to print error
    err = norm(Y - (Dksvd * Cksvd))^2 / length(Y)
    println("Error $i: $err")
    
    Csp = SC_SP(Y, Dksvd, Cksvd, s)
    Dksvd, Cksvd = DU_KSVD(Y, Dksvd, Csp)


end
# println(Dksvd[1, :])
# println(Cksvd[1, :])


Error 1: 6.098968329845044
Error 2: 0.21625944017963128
Error 3: 0.1587916630315628
Error 4: 0.1404088375523666
Error 5: 0.13039848853662805
Error 6: 0.12551104703914268
Error 7: 0.12246589852627476
Error 8: 0.12016289873725121
Error 9: 0.11812139004217556
Error 10: 0.11651055676906798
Error 11: 0.11447769121728597
Error 12: 0.11318627673618387
Error 13: 0.11193183499451108
Error 14: 0.11126316153194585
Error 15: 0.10995316044265498
Error 16: 0.10922968111334169
Error 17: 0.1077088435539022
Error 18: 0.1077729127636369
Error 19: 0.10601026859786143
Error 20: 0.10700463053507105
Error 21: 0.10782564565187401
Error 22: 0.11002495542969908
Error 23: 0.11175366515779504
Error 24: 0.11248773067930531
Error 25: 0.11386549158825357
Error 26: 0.11583064049871325
Error 27: 0.11730106438208049
Error 28: 0.11656333829884799
Error 29: 0.11759286096135418
Error 30: 0.11663222007161662
Error 31: 0.1149034779233069
Error 32: 0.11256362988773194
Error 33: 0.10829329286848399
Error 34: 0.10663649985970

### 3

In [28]:
function f_and_gradf(Y, D, C)
    f = (norm(Y - (D * C)))^2
    grad = 2 * adjoint(D) * (Y - (D*C))
    norm_grad = norm(grad)

    println("f: $f, normgrad: $norm_grad")

    return f, norm_grad
end

# Initialisation
iter = 50
Dksvd = D0
Cksvd = C0

for i in 1:iter
    f_and_gradf(Y, Dksvd, Cksvd)
    Csp = SC_SP(Y, Dksvd, Cksvd, s)
    Dksvd, Cksvd = DU_KSVD(Y, Dksvd, Csp)


    # Uncomment to print error
    # err = norm(Y - (Dcur * Ccur))^2 / length(Y)
    # println("Error $i: $err")
end

f: 24981.3742790453, normgrad: 465.3155963309245
f: 885.7986669757697, normgrad: 86.60791036175678
f: 650.4106517772813, normgrad: 71.7377632369515
f: 575.1145986144936, normgrad: 67.36155923447986
f: 534.1122090460285, normgrad: 64.28235580596383
f: 514.0932486723284, normgrad: 63.385709731847584
f: 501.62032036362143, normgrad: 62.28894199667987
f: 492.18723322778095, normgrad: 61.78412525485747
f: 483.8252136127511, normgrad: 60.99650482998314
f: 477.22724052610243, normgrad: 60.7712893204894
f: 468.90062322600335, normgrad: 59.73982650339105
f: 463.6109895114091, normgrad: 59.574530014034735
f: 458.4727961375174, normgrad: 58.77488886459419
f: 455.7339096348502, normgrad: 58.849141940817205
f: 450.3681451731148, normgrad: 57.84248901648582
f: 447.40477384024757, normgrad: 57.88569958047387
f: 441.1754231967834, normgrad: 56.95854106920298
f: 441.43785067985675, normgrad: 57.230297172182325
f: 434.2180601768404, normgrad: 56.06468217836796
f: 438.290966671651, normgrad: 56.564695469