# Coursework 2

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [1]:
using JLD2,FileIO

In [2]:
Base.@kwdef mutable struct CourseWork_2
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    
    # 7.1 Estimation Accuracy
    
    Q7_1_data_A::Matrix{Float64}
    
    Q7_1_a_ans_w::Union{Missing,Vector}
    Q7_1_a_ans_err::Union{Missing,Float64}
    Q7_1_b_ans_w::Union{Missing,Vector}
    Q7_1_b_ans_err::Union{Missing,Float64}
    Q7_1_c_ans_err::Union{Missing,Float64}
    
     # 7.2 Greedy Algorithms
    
    Q7_2_1_data_y::Vector
    Q7_2_1_data_A::Matrix
    Q7_2_1_data_S::Int
    
    Q7_2_1_ans_x::Union{Missing,Vector}
    
    Q7_2_2_data_y::Vector
    Q7_2_2_data_A::Matrix
    Q7_2_2_data_S::Int
    
    Q7_2_2_ans_x::Union{Missing,Vector}
    
    Q7_2_3_data_y::Vector
    Q7_2_3_data_A::Matrix
    Q7_2_3_data_S::Int
    
    Q7_2_3_ans_x::Union{Missing,Vector}
    
    # 8.1 The MOD Method
    
    Q8_1_data_Y::Matrix
    Q8_1_data_D0::Matrix
    Q8_1_data_C0::Matrix
    Q8_1_data_s::Int
    
    Q8_1_1_ans_Comp::Union{Missing,Matrix}
    Q8_1_2_ans_Csp::Union{Missing,Matrix}
    Q8_1_3_ans_Dmod::Union{Missing,Matrix}
    Q8_1_4_ans_C50::Union{Missing,Matrix}
    Q8_1_4_ans_D50::Union{Missing,Matrix}
    Q8_1_5_ans_f::Union{Missing,Vector}
    Q8_1_5_ans_gradf::Union{Missing,Vector}
    
    # 8.2 The K-SVD Method
    
    Q8_2_data_Y::Matrix
    Q8_2_data_D0::Matrix
    Q8_2_data_C0::Matrix
    Q8_2_data_s::Int
    
    Q8_2_1_ans_Ckscd::Union{Missing,Matrix}
    Q8_2_1_ans_Dkscd::Union{Missing,Matrix}
    Q8_2_2_ans_C50::Union{Missing,Matrix}
    Q8_2_2_ans_D50::Union{Missing,Matrix}
    Q8_2_3_ans_f::Union{Missing,Vector}
    Q8_2_3_ans_gradf::Union{Missing,Vector}
    
    
end

CourseWork_2

In [3]:



A = JLD2.load("Banthia Dev2016674StudentFile.jld2");

A = A["CourseWork_2"];



## 7.1. Estimation Accuracy


### 1. (a)

In [4]:

using LinearAlgebra

A_matrix = A.Q7_1_data_A
A_hat = inv(adjoint(A_matrix) * A_matrix) * adjoint(A_matrix)
A_hat_SVD = svd(A_hat)

S = A_hat_SVD.S
V = A_hat_SVD.V

w_min = V[:, end]
println(norm(w_min))
println(w_min)

sol = adjoint(A_hat * w_min) * (A_hat * w_min)
println(sol)


A.Q7_1_a_ans_w = w_min
A.Q7_1_a_ans_err = sol
    

1.0000000000000002
[-0.2866099316323966, -0.2735738869456807, -0.275110332495816, -0.20254052359632677, -0.2515659391520371, -0.22606783496258134, -0.2761186333557751, -0.2399296776494263, -0.19563446414287952, -0.23339617662630685, -0.2682096462421956, -0.165995290218401, -0.207326456778322, -0.2788299794964844, -0.28429676890894295, -0.29036414996088245]
0.00028370828602538244


0.00028370828602538244

### 1. (b)

In [5]:
A_matrix = A.Q7_1_data_A
A_hat = inv(adjoint(A_matrix) * A_matrix) * adjoint(A_matrix)
A_hat_SVD = svd(A_hat)

S = A_hat_SVD.S
V = A_hat_SVD.V

w_max = V[:, 1]
println(norm(w_max))
println(w_max)

sol = adjoint(A_hat * w_max) * (A_hat * w_max)

A.Q7_1_b_ans_w = w_min
A.Q7_1_b_ans_err = sol

1.0
[-0.4552312129964472, 0.07073956179615414, 0.3987116565300202, 0.24144750465687437, -0.41822896470571663, -0.1316152502311507, 0.33880031853825254, 0.02349555077187621, -0.020577965325504172, -0.07887855551702329, -0.2117833851648671, 0.43447884650810575, 0.0815114992742374, -0.002431966292329101, 0.0468439503381529, -0.11748656375624197]


83372.11243034284

### 1. (c)

In [6]:

A_hat = inv(adjoint(A_matrix) * A_matrix) * adjoint(A_matrix)
# Using expectation of quadratic form
Exp = tr(adjoint(A_hat) * A_hat) / size(A_hat, 1)

5448.141452741144

## 7.2. Greedy Algorithms

### 1

In [4]:
using LinearAlgebra


y = A.Q7_2_1_data_y
A_matrix = A.Q7_2_1_data_A
S = A.Q7_2_1_data_S


function compute_best_fit_solution(X, y)
    return X \ y  
end

function expand_support(A, y, k, sparse_set)
    correlation = A' * y
    top_k = partialsortperm(abs.(correlation), length(correlation) - k + 1:length(correlation))
    sparse_set = union(sparse_set, Set(top_k))

    return sparse_set
end

function OMP(A, y, S)
    sparse_set = Set{Int}()
    residual = y
    sparse_solution = zeros(size(A, 2))
    x_hat = zeros(length(S))

    for i in 1:S

        correlation = A' * residual
        S_max = argmax(abs.(correlation))
        push!(sparse_set, S_max)

        col_indices = collect(sparse_set)
        A_subset = A[:, col_indices]

        x_hat = compute_best_fit_solution(A_subset, y)
        residual = y - A_subset * x_hat

    end

    for (i, j) in zip(sparse_set, x_hat)
        sparse_solution[i] = j
    end

    return sparse_solution
end

sparse_solution = OMP(A_matrix, y , S)
residual = y - A_matrix * sparse_solution
A.Q7_2_1_ans_x = sparse_solution
println(sum(abs.(residual)))
    

0.29079879920876656


### 2

In [5]:
y = A.Q7_2_2_data_y
A_matrix = A.Q7_2_2_data_A
S = A.Q7_2_2_data_S

function SMP(A, y, k, C = nothing)

    sparse_set = Set()
    sparse_solution = zeros(size(A, 2))

    if C == nothing 
        sparse_set = expand_support(A, y, k, sparse_set)
  

    else
        residual = y - A*C
        sparse_set = expand_support(A, residual, k, sparse_set)
    end

    A_subset = A[:, collect(sparse_set)]
    x_hat = compute_best_fit_solution(A_subset, y)
    residual = y - A_subset * x_hat
    println(sum(abs.(residual)))


    n = 10
    for i in 1:n 
        sparse_set = expand_support(A, residual, k, sparse_set)
        A_subset = A[:, collect(sparse_set)]
        x_hat = compute_best_fit_solution(A_subset, y)
        
        # Get k most significant indices
        println(sum(abs.(residual)))
        k_most_significant_x = partialsortperm(abs.(x_hat), 1:k, rev=true)
        sparse_set = Set(collect(sparse_set)[k_most_significant_x])
        
        A_subset = A[:, collect(sparse_set)]
        x_hat = compute_best_fit_solution(A_subset, y)
        residual = y - A_subset * x_hat
    end

    for (i, j) in zip(sparse_set, x_hat)
        sparse_solution[i] = j
    end

    return sparse_solution

end

A.Q7_2_2_ans_x = SMP(A_matrix, y, 5)
    



5.21858810374375
5.21858810374375
2.0705292004563365
0.326952962154961
0.326952962154961
0.326952962154961
0.326952962154961
0.326952962154961
0.326952962154961
0.326952962154961
0.326952962154961


82-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 1.1510996632118482
 0.0
 0.0
 0.0
 0.0
 0.0

### 3

In [6]:
using LinearAlgebra

y = A.Q7_2_3_data_y
A_matrix = A.Q7_2_3_data_A
S = A.Q7_2_3_data_S

function HIT(A, y, k)
    x = zeros(size(A, 2)) 

    for i in 1:10000

        residual = y - A_matrix * x
        println(sum(abs.(residual)))
        x -= 0.01 * (A' * (A * x - y))

        top_k_indices = partialsortperm(abs.(x), length(x) - k + 1:length(x))
        x[setdiff(1:end, top_k_indices)] .= 0
    end

    return x
end


A.Q7_2_3_ans_x = HIT(A_matrix, y, S)


14.335586542102346
14.140051814452294
13.94835407517065
13.760412758204184
13.576149021241187
13.395485708648675
13.2183473152075
13.050260911951948
12.898139314067603
12.748928693440778
12.602568374406895
12.458998976998036
12.31816238909672
12.1800017391891
12.044461369704687
11.911486810930013
11.792308487885872
11.682559928771356
11.574808266069187
11.469012522107528
11.365132590558392
11.263129217732287
11.16296398427542
11.064599287260798
10.967998322664695
10.873125068220235
10.779944266639959
10.688421409199382
10.59852271967387
10.510215138621096
10.43080096427119
10.355865712864006
10.282230950732709
10.209870408229333
10.138758371792244
10.068869672023725
10.00017967202403
9.932664255976412
9.866299817977668
9.801063251108978
9.736931936741824
9.673883734073916
9.611896969890234
9.55095042854425
9.491023342154694
9.432095381013115
9.374146644197795
9.317157650389488
9.261109328884725
9.205983010802347
9.151760420479173
9.09842366705069
9.0459552362128
8.994337982160719
8.943

64-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 1.1945843595890293
 0.0
 0.0
 0.0
 0.0
 0.0

## 8.1. The MOD Method

### 1

In [7]:
Y = A.Q8_1_data_Y
D0 = A.Q8_1_data_D0
C0 = A.Q8_1_data_C0
s = A.Q8_1_data_s

function construct_C_omp(D0, Y, s)

    num_rows = size(D0, 2)
    num_cols = size(Y, 2)
    C_omp = zeros(num_rows, num_cols)

    for i in 1:num_cols
        sparse_col = OMP(D0, Y[:,i], s)
        C_omp[:, i] = sparse_col
    
    end

    return C_omp

end
    

C_omp = construct_C_omp(D0, Y, s)
A.Q8_1_1_ans_Comp = C_omp
residual = abs.(Y - D0*C_omp)




32×128 Matrix{Float64}:
 0.431969   0.445521   0.286003   …  0.684156   0.463265    0.265545
 1.44472    0.741369   0.441393      0.506254   1.15642     0.0320312
 0.0130437  0.0843351  0.609548      0.475165   0.0597012   0.0900556
 0.613865   0.0111185  0.600934      0.763565   0.706549    0.692635
 0.101882   0.158697   0.0702224     0.556071   0.0196554   1.42091
 0.945675   0.486042   0.61059    …  0.208293   0.853642    0.131697
 0.740702   0.047723   0.644869      0.591949   0.0687498   1.6903
 0.0180573  0.736449   0.0583149     1.10808    0.278971    0.177191
 0.27692    0.309834   0.109563      0.424654   0.172227    1.2826
 0.0438059  0.593209   0.0216041     0.189033   0.282592    0.635048
 ⋮                                ⋱  ⋮                      
 0.475181   0.365103   0.228175      1.0062     1.756       1.7583
 0.42474    0.509534   0.412073      0.620553   0.218747    0.532209
 0.55051    0.262746   0.796926   …  0.324216   0.133913    0.0243298
 1.22777    0.410267  

### 2

In [12]:
function construct_C_smp(D0, Y, s, C0 = nothing)

    num_rows = size(D0, 2)
    num_cols = size(Y, 2)
    C_smp = zeros(num_rows, num_cols)

    for i in 1:num_cols

        if C0 != nothing
            sparse_col = SMP(D0, Y[:,i], s, C0[:, i])
        else
            sparse_col = SMP(D0, Y[:,i], s)
        
        end

        C_smp[:, i] = sparse_col
    
    end

    return C_smp

end

residual = abs.(Y - D0*C0)
println(sum(residual))


C_smp = construct_C_smp(D0, Y, s, C0)
A.Q8_1_2_ans_Csp = C_smp
residual = abs.(Y - D0*C_smp)
println(sum(residual))

2212.610225983941
19.147639690713522
19.147639690713522
16.07603667889843
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
21.04127275997496
21.04127275997496
15.074278232266213
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
23.030764970075477
23.030764970075477
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
19.854407800202942
19.854407800202942
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
21.667685252067116
21.667685252067116
19.49961138367266
19.7074415262587
18.38560014774302
17.90471858833395
17.90471858833395
17.90471858833395
17.904718588

### 3

In [13]:
using LinearAlgebra

function DU_mod(Y, C)

    D = (Y * C' * pinv(C * C'))
    
    for col in 1:size(D, 2)
        col_norm = norm(D[:, col], 2)  
        if col_norm != 0                     
            D[:, col] .= D[:, col] / col_norm
        end
        return  D
    end
end

D1 = DU_mod(Y, C0)

A.Q8_1_3_ans_Dmod = D1


32×64 Matrix{Float64}:
  0.319025     0.302134   -0.0424106   …  -0.128956   -0.0603972
 -0.0719639    0.265046   -0.0239047      -0.0583289  -0.193578
 -0.215347    -0.0210695   0.190927       -0.434875    0.0403859
 -0.156016    -0.216038    0.326015       -0.0669642  -0.120874
  0.00436522  -0.0407587  -0.27126         0.0707854  -0.213005
  0.074193    -0.090959    0.0315206   …   0.0117929   1.29212e-5
 -0.0307149    0.068503    0.0752087       0.183012   -0.563121
  0.036672     0.0185513  -0.211475        0.12697     0.255107
  0.157343     0.307087    0.00521545     -0.0806868   0.441349
 -0.0391604   -0.275471    0.175225       -0.244411    0.0851642
  ⋮                                    ⋱              
 -0.376045     0.227891   -0.307387        0.219808   -0.284362
 -0.0991814   -0.34443     0.283508       -0.320839   -0.300049
 -0.0455902   -0.440005    0.00423046  …   0.0145572  -0.209898
  0.220225     0.0593033   0.216849       -0.215023    0.212263
  0.0590787   -0.0766

### 4

In [14]:
function MOD(Y, D0, C0)

    D = D0
    C_smp = C0
    error_vec = zeros(50)
    grad_vec = zeros(50)
    for i in 1:50
        
        error, grad = compute_error_and_error_gradient(Y, D, C_smp)
        error_vec[i] = error
        grad_vec[i] = grad
        C_smp = construct_C_smp(D, Y, s, C_smp)
        D = DU_mod(Y, C_smp) 

    end

    return C_smp, D, error_vec, grad_vec
end

C_smp, D, error_vec, grad_vec = MOD(Y, D0, C0)
A.Q8_1_4_ans_C50 = C_smp
A.Q8_1_4_ans_D50 = D
A.Q8_1_5_ans_f = error_vec
A.Q8_1_5_ans_gradf = grad_vec



19.147639690713522
19.147639690713522
16.07603667889843
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
16.24717273274976
21.04127275997496
21.04127275997496
15.074278232266213
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
13.203790328818895
23.030764970075477
23.030764970075477
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
18.750721237840818
19.854407800202942
19.854407800202942
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
18.373581860404883
21.667685252067116
21.667685252067116
19.49961138367266
19.7074415262587
18.38560014774302
17.90471858833395
17.90471858833395
17.90471858833395
17.90471858833395
17.904718588

Excessive output truncated after 524296 bytes.

7.3582219109675435
7.3582219109675435
7.3582219109675435
7.3582219109675435
7.3582219109675435
23.420091880124875
23.420091880124875
11.49079461213087
6.370479912614281
6.370479912614281
6.370479912614281
6.370479912614281
6.370479912614281
6.370479912614281
6.370479912614281
6.370479912614281
18.824875724940842
18.824875724940842
12.593462769841956
9.991022426341079
7.790878876984526
7.790878876984526
7.790878876984526
7.790878876984526
7.790878876984526
7.790878876984526
7.790878876984526
18.168105776676793
18.168105776676793
10.289644328154258
7.975943224637232
7.6377707355438655
7.6377707355438655
7.6377707355438655
7.6377707355438655
7.6377707355438655
7.6377707355438655
7.6377707355438655
21.369800832994137
21.369800832994137
12.29945162307416
8.041693663633962
5.361886768551777
5.361886768551777
5.361886768551777
5.361886768551777
5.361886768551777
5.361886768551777
5.361886768551777
19.92286555715969
19.92286555715969
15.510952527656476
14.80734905526217
13.47418250338092
12.22

50-element Vector{Float64}:
  90.43896136383484
 104.30640895034942
  92.71592965148479
  97.27253293965215
  97.46013736216192
  95.48907414813772
  99.26637735593066
 100.61144555253564
 100.6608322642669
  99.98886092911209
   ⋮
 152.58765388825958
 158.2646744550593
 157.3818528365768
 157.7759063146536
 161.21089937217988
 164.4676144604147
 159.94793392064665
 153.82044922961757
 169.80471249234725

### 5

In [15]:
function compute_error_and_error_gradient(Y, D, C)

    error_frobenius_norm = norm(Y - D*C, 2)
    gradient_frobenius_norm =  norm(D' * (2 * (D * C - Y)), 2)

    return error_frobenius_norm, gradient_frobenius_norm 

end

#this cell (4) must be executed before (5)

compute_error_and_error_gradient (generic function with 1 method)

## 8.1. The K-SVD Method

### 1

In [20]:
using LinearAlgebra

function DU_KSVD(Y, D, C)
    num_row, num_col = size(D)

    for i in 1:num_col
        subset = [j for j in 1:num_col if j != i]
        D_subset = D[:, subset]
        C_subset = C[subset, :]

        E_k = Y - D_subset * C_subset
        U, σ, V = svd(E_k; full = false)

        d_k = U[:, 1]  
        d_k /= norm(d_k)          
        x_k = σ[1] * V'[1, :]  


        D[:, i] = d_k
        C[i, :] = x_k

    end

    return D, C
end

D, C = DU_KSVD(Y, D0, C0)
A.Q8_2_1_ans_Ckscd = C
A.Q8_2_1_ans_Dkscd = D



32×64 Matrix{Float64}:
  0.10443     0.00842242   0.0158474   …  -0.0847553  -0.0236777    0.194231
 -0.0619045   0.0714532   -0.430589       -0.04894     0.286525    -0.16088
  0.199317    0.0370993    0.0489496       0.030944   -0.203726    -0.0781021
  0.115553   -0.0359598   -0.04766        -0.26276     0.267131     0.0721546
  0.0460444  -0.05027     -0.00975367     -0.151928   -0.0486666    0.220647
  0.0984098  -0.168034    -0.256986    …   0.11812    -0.0167585   -0.235799
 -0.202799   -0.0466211    0.0217594       0.129151    0.324845     0.116236
 -0.0677662  -0.251213     0.252962       -0.0501725   0.0791467    0.0518925
  0.197759   -0.0289704   -0.0125874       0.0529665  -0.0280998    0.0761102
 -0.144743    0.346346    -0.228217       -0.220483   -0.00416006   0.0782525
  ⋮                                    ⋱                           
 -0.127211   -0.22917      0.0890756       0.095546    0.291741     0.35037
 -0.0467493  -0.0251732    0.171723        0.0669843  -0.00

### 2

In [21]:
function K_SVD(Y, D0, C0)

    D = D0
    C_smp = C0
    error_vec = zeros(50)
    grad_vec = zeros(50)
    
    for i in 1:50

        error, grad = compute_error_and_error_gradient(Y, D, C_smp)
        error_vec[i] = error
        grad_vec[i] = grad
   
        C_smp = construct_C_smp(D, Y, s, C_smp)
        D, C_smp = DU_KSVD(Y, D, C_smp)

    end

    return C_smp, D, error_vec, grad_vec
end

C , D, error_vec, grad_vec = K_SVD(Y, D0, C0)



A.Q8_2_2_ans_C50 = C
A.Q8_2_2_ans_D50 = D
A.Q8_2_3_ans_f = error_vec
A.Q8_2_3_ans_gradf = grad_vec



BoundsError: BoundsError: attempt to access 32×0 Matrix{Float64} at index [1:32, 1]

### 3

In [17]:
A.Plagiarism_declare = true
A.CID = 02016674
 

jldopen("BanthiaDev02016674StudentFile.jld2", "w") do file

   write(file, "CourseWork_2", A)

end